site_name: Bhakti Wiki
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.instant.progress
    # - navigation.tabs
    # - navigation.tabs.sticky
  language: en
  palette: 
  
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  plugins:
      - mkdocs-video